build(deps): workaround jbundler/maven-tools > virtus > axiom-types lack of Ruby 3.4 compatibility
Wihout this, the normal tests work, however the integration tests fail before being invoked during `Execution default-package of goal org.jruby.maven:gem-maven-plugin:3.0.6:package` which seem to rely on maven-tools to parse the integration test POM before invoking it. Seemed the best place to declare the dependency was here, since this is where jbundler and implicitly maven-tools are defined, although declaring it in the Mavenfile also seems to work.

LoadError: cannot load such file -- bigdecimal
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at /Users/chad/.m2/repository/org/jruby/maven/ruby-tools/3.0.6/ruby-tools-3.0.6.jar!/axiom/types.rb:3
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at /Users/chad/.m2/repository/org/jruby/maven/ruby-tools/3.0.6/ruby-tools-3.0.6.jar!/axiom-types.rb:3
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at /Users/chad/.m2/repository/org/jruby/maven/ruby-tools/3.0.6/ruby-tools-3.0.6.jar!/virtus.rb:245
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at /Users/chad/.m2/repository/org/jruby/maven/ruby-tools/3.0.6/ruby-tools-3.0.6.jar!/maven/tools/model.rb:1
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at /Users/chad/.m2/repository/org/jruby/maven/ruby-tools/3.0.6/ruby-tools-3.0.6.jar!/maven/tools/pom.rb:22
  require at org/jruby/RubyKernel.java:1193
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:139
   <main> at -e:1