check if jruby-jars / jruby-rack has been loaded before requiring
this is necessary in a Bundler centric world as if one is trying to pack with a pre-release
jruby-jars gem - outside of the application bundle

`ruby -rjruby-jars -S warble` should simply work 

except that doesn't since the time require lines are reached they get routed via Bundler

```
warble aborted!
LoadError: no such file to load -- jruby-jars
app/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `block in require'
app/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:240:in `load_dependency'
app/vendor/bundle/jruby/2.2.0/gems/activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/traits/war.rb:71:in `default_jar_files'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/traits/war.rb:137:in `move_jars_to_webinf_lib'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/traits/war.rb:79:in `update_archive'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/traits.rb:41:in `block in update_archive'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/traits.rb:41:in `update_archive'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/jar.rb:170:in `apply_traits'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/jar.rb:148:in `apply'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/task.rb:118:in `block in define_files_task'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/task.rb:94:in `block in define_main_task'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/task.rb:93:in `block in define_main_task'
/opt/local/rvm/gems/jruby-9.0.5.0@predicsis/gems/warbler-2.0.0.rc2/lib/warbler/application.rb:77:in `run'
warble:16:in `<top>'
Tasks: TOP => war:files

```